### ISSUE TITLE
Highlight `in`, `isa`

### ISSUE THREAD

**Issue by cossio** [JuliaEditorSupport/atom-language-julia#151]
The editor should highlight `in`, `isa` when used as infix operators.

**Comment by dawbarton** [comment]
I just had a look at this (because I came here with the same issue in mind) and it looks like `in` and `isa` are correctly identified as operators but there is a clash of different styles in the CSS stylesheet since they are identified as multiple different things (keyword, operator, and relation); it ends up with the keyword+operator (combined) style overwriting the keyword style. Trouble is that all the styling is defined by your current syntax theme and not language-julia.

One potential fix would be to remove the operator identifier for `in` and `isa` and so have it fall back to the keyword style but I don't know what knock-on effects this would have.

In the meantime there is a quick fix by adding
```css
.syntax--relation {
    color: #a626a4 !important;
}
```
to your `styles.less` file (File menu -> Stylesheets in Atom); obviously replace the color with whatever works with your current syntax theme.

**Comment by dawbarton** [comment]
I got that slightly wrong; `in` gets identified as a relation whereas `isa` gets identified as isa. So the following CSS is required
```css
.syntax--relation {
    color: #a626a4 !important;
}
.syntax--isa {
    color: #a626a4 !important;
}
```

**Comment by cossio** [comment]
This fix won't work from VS Code, right?

**Comment by pfitzseb** [comment]
`in` and `isa` are now tokenized as operators.

**Comment by Datseris** [comment]
Hi @pfitzseb , this does not seem to work yet:

![highlighting](https://user-images.githubusercontent.com/19669089/65832445-1d9ff380-e2c4-11e9-92c7-d93f9587d5f5.PNG)

I am running latest stable Julia/Juno/Atom and Windows 10. I expected both `isa` and `in` to have different highlight as the normal variables.

**Comment by aviatesk** [comment]
Those operators are tokenized by this grammar package, but maybe your syntax theme didn't setup syntax color for them.

Use the other package, or define something like below in your stylesheet:
```less
.syntax--source {
  // julia
  &.syntax--julia {
    .syntax--operator {
      color: white; // the color your want
    }
  }
}
```

(ref: https://github.com/aviatesk/avi-atom/blob/master/styles.less#L94-L119)
